### ISSUE TITLE
Command display

### ISSUE THREAD

**Issue by NorthernL1ghts** [rasitxy/rflct-web-ui#2]
This is great way to demonstrate the different possible commands for the user to play around with. However, the text disappears after a short period of time. This could be increased (added delay) so the user can understand what the commands do and how to interact with the AI using them. 

Solution -> Add delay to make the text last longer on screen, or make the user run a command to make the text disappear. Such as /help show and /help remove?

**Comment by rasitxy** [comment]
Added a disappearance delay to make text last longer on screen.
And yes, we can also consider something like a command to disappear the info text of commands like help and cmds.

Thanks!
